### PR TITLE
 Updated Record Layer section

### PR DESCRIPTION
**Pull request by hannestschofenig**

### CODE REVIEW

File: draft-ietf-tls-dtls-connection-id.md [hunk 1]
```diff
@@ -229,22 +229,41 @@ zeroes
...
-                            DTLSWrappedCompressed.length +
-                            DTLSWrappedCompressed.fragment);
-   where "+" denotes concatenation.
+    additional_data = seq_num + DTLSWrappedCompressed.type + 
+	                  DTLSCompressed.version + DTLSCompressed.length + 
+					  cid + cid_length + cid_codepoint + 
+					  DTLSWrappedCompressed.length + 
+					  DTLSWrappedCompressed.fragment;
+					  
+    where "+" denotes concatenation.
```
Comment (boaks) [inline draft-ietf-tls-dtls-connection-id.md:274]: Why should `DTLSWrappedCompressed.type` be included, it's contained in the encrypted part?
Why both, `DTLSCompressed.length` and `DTLSWrappedCompressed.length`, should be included?
(By the way, I don't know, what  `DTLSWrappedCompressed.length` is. It's not defined in the `DTLSWrappedCompressed` struct.)

Comment (hannestschofenig) [reply draft-ietf-tls-dtls-connection-id.md:274]: I modified the list of fields in the additional data calculation.

Comment (boaks) [reply draft-ietf-tls-dtls-connection-id.md:274]: The tls `seq_num` of https://tools.ietf.org/html/rfc5246#section-6.2.3.3 is in my opinion not the dtls `seq_num` of https://tools.ietf.org/html/rfc6347#section-4.1 ! Please don't remove the `epoch` field.

Comment (boaks) [reply draft-ietf-tls-dtls-connection-id.md:274]: Uups, sorry forget the upper comment about the epoch! I read the last commit in isolation ;-(.

Comment (thomas-fossati) [reply draft-ietf-tls-dtls-connection-id.md:274]: Thanks Hannes, looks good to me.

PS: not that it makes any difference, but adding the fields in the order in which they appear in the header
```
   seq_num + type + version + cid_length + cid + length
```
looks slightly more consistent with the previously established convention?

Comment (thomas-fossati) [reply draft-ietf-tls-dtls-connection-id.md:274]: Another small note: I think we should not remove the MAC computation.  I understand we want to move to an AEAD-only world, but this needs to work with every mode supported in 1.2...

Comment (boaks) [reply draft-ietf-tls-dtls-connection-id.md:274]: > PS: not that it makes any difference, but adding the fields in the order in which they appear in the header

There is no field `cid_length` in the header :-).

Comment (hannestschofenig) [reply draft-ietf-tls-dtls-connection-id.md:274]: While there is no such field in the header that doesn't mean we cannot include it in the additional data calculation.

Comment (hannestschofenig) [reply draft-ietf-tls-dtls-connection-id.md:274]: Thomas, if you can add the text for the other MAC calculations then that's fine with me. I only care about the AEAD ciphers since we recommend them in the DTLS / TLS IoT profiles draft.

Comment (boaks) [reply draft-ietf-tls-dtls-connection-id.md:274]: > While there is no such field in the header that doesn't mean we cannot include it in the additional data calculation.

Sure, but why should it then be added?

Comment (boaks) [reply draft-ietf-tls-dtls-connection-id.md:274]: Which size is considered for the `cid_length`? The same as in the extension (`opaque cid<0..2^8-1>`, so 1 byte as `uint8`)?

Comment (hannestschofenig) [reply draft-ietf-tls-dtls-connection-id.md:274]: It would be 1 byte length but your remark is fair. IMHO one would have to do a formal analysis to say whether it really has to be added or not. Currently, we are just adding fields to the additional data / MAC calculation without much justification

Comment (boaks) [reply draft-ietf-tls-dtls-connection-id.md:274]: OK, thanks! That helps me to understand the current definition.

Comment (hannestschofenig) [reply draft-ietf-tls-dtls-connection-id.md:274]: I updated the additional_data calculation again. I removed the cid_length since it is only implicit and I have re-ordered the fields as they appear on the wire.

Comment (hannestschofenig) [reply draft-ietf-tls-dtls-connection-id.md:274]: Corrected the order again since the seq_nr was used as the initial value in RFC 7366, even though this is not how it is represented on the wire.

File: draft-ietf-tls-dtls-connection-id.md [hunk 2]
```diff
@@ -255,25 +255,37 @@ Other fields are defined in RFC 6347. Note that this specification does
...
+: This value contains the outer-header content type, i.e. the tls12_cid. 
+
+version
+: This value contains the version number. 
+
+length
+: This value contains the length information in the outer-header. 
 
+cid
+: Value of the connection id.
```
Comment (thomas-fossati) [inline draft-ietf-tls-dtls-connection-id.md]: I'd rather say "Value of the *negotiated* connection id" to distinguish it from what is sent on the wire.  And it's maybe worth adding something like "Note that this is empty in case a 0-length CID has been negotiated".

I'd also add an entry for cid_length here, specifying that even if a 0-length CID has been negotiated, and therefore no CID appears on the wire, a cid_length of 0 MUST be added to the AD.

Comment (hannestschofenig) [reply draft-ietf-tls-dtls-connection-id.md]: I added that text

**Review by jsalowey — APPROVED** [review]
These changes look appropriate.

File: draft-ietf-tls-dtls-connection-id.md (hunk 2 above)
Comment (boaks) [reply draft-ietf-tls-dtls-connection-id.md]: Sorry, if the usage of "empty CID" with the new record type is intended to obfuscate the payload length, this is clearly a new use-case and obvious no NAT solution!

So, please add this new use-case explicit to the introduction!

And please provide an example, which shows that adding the cid_length make sense!
In other discussion "empty CID in the new record types" are denied.

**Comment by boaks** [comment]
> These changes look appropriate.

According https://github.com/tlswg/dtls-conn-id/issues/28#issuecomment-458032109

> As I said, empty CID should mean "use the 6347 framing"

this is obvious far away from "appropriate".

I would appreciate, if the scope of this draft could be clarified, before adding additional features.

File: draft-ietf-tls-dtls-connection-id.md (hunk 2 above)
Comment (thomas-fossati) [reply draft-ietf-tls-dtls-connection-id.md]: There is no new "payload length obfuscation" use case that is enabled by this change.

I think you are confusing on-the-wire framing with how authentication data is computed.

Hannes's change here is only about MAC computation.  The gist is that 0-length CIDs have 6347 framing but their MAC is computed slightly differently from a "normal" 6347 record.

Comment (boaks) [reply draft-ietf-tls-dtls-connection-id.md]: Hm, so want you to ensure, that if a empty CID is used in the Hello Extension, and therefore a RFC 6347 record is used later, the MAC is different compared to a RFC 6347 record, which is used without using a empty cid in the Hello Extension?

Why? What would be the advantage? What are the examples, which show this advantage?

FMPOV: the MAC includes already much keying material, the cid_length willl hardly improve that. From the discussion in #25 two arguments for including the MAC have been named: 

https://github.com/tlswg/dtls-conn-id/issues/25#issuecomment-444890710

"Yes, but it might be true with some extension in the future. Moreover, authenticating the whole header is just good practice."

I simply just don't see the justification, to complicate RFC6347 MAC calculations.

Comment (boaks) [reply draft-ietf-tls-dtls-connection-id.md]: > There is no new "payload length obfuscation" use case that is enabled by this change.

In my opinion, this https://github.com/tlswg/dtls-conn-id/issues/22#issuecomment-458758785 indicates, that it is a use-case :-).

Therefore I started #40 .

**Comment by hannestschofenig** [comment]
The issue you raised in https://github.com/tlswg/dtls-conn-id/issues/28#issuecomment-458032109 is important and will be addressed in a separate PR. I would like to merge some of the PRs to that we do not have too many conflicts. This PR only provides the text for the additional_data and, since we have changed our mind about it so many times already, I would like to get it into the working draft. Then, Thomas can make a contribution for the MAC calculation for non-AEAD ciphers.

**Comment by boaks** [comment]
@hannestschofenig 

Thank you very much for great patience! 
It's sure still easy to implement, even with a new MAC for the old RFC 6347 record. 
As I tried to point out, if there are new use-cases, they should not be obfuscated by introducing only "maverick fields" somewhere, in my opinion, they should be addressed clearly. 

I still see no argument to include the cid_length into the MAC.
